### ISSUE TITLE
Wrong windows path

### ISSUE THREAD

**Issue by sainnhe** [yaegassy/coc-pydocstring#1]
The executable in windows is not `~/AppData/Local/coc/extensions/coc-pydocstring-data/doq/venv/bin/doq`, it should be `~/AppData/Local/coc/extensions/coc-pydocstring-data/doq/venv/Scripts/doq.exe`.

**Comment by sainnhe** [comment]
Btw, you should use `/path/to/python -m pip install --upgrade pip` instead of `/path/to/pip install --upgrade pip` in windows, otherwise it will report a permission error.

**Comment by yaegassy** [comment]
Thank you for the issue report, I hadn't checked because I don't use Windows regularly.

I will consider fixing the Windows support at a later date.

(In addition to venv, we also need a process to check if the python command is python3.x or not.)
