### ISSUE TITLE
Method to install doq without prompt

### ISSUE THREAD

**Issue by R-Broadley** [yaegassy/coc-pydocstring#12]
I run nvim in a container so would like to be able to get doq installed when building the image using a command like:

```
RUN nvim --headless -c ":CocCommand pydocstring.install" +qa
```

Is there a way to tell if nvim is running in headless mode and call `doqInstall` directly instead of `installWrapper`?

**Comment by yaegassy** [comment]
Hi, I have checked the your issue report.

Unfortunately, I do not know how to determine if nvim is running in headless mode. 🙇

If I find out how to distinguish them, I will consider adjusting the function, but it may not be possible to execute the commands provided by the extension at startup.

**Comment by yaegassy** [comment]
It is now possible to install without a prompt, so we will close this issue.
