### ISSUE TITLE
TypeError: document.getText is not a function

### ISSUE THREAD

**Issue by xavier-balesi** [yaegassy/coc-pydocstring#15]
Hi,
thank you for the plugin, it seems very cool.

I have an error when I run (coc-codeaction-line) then `Add docstring for "Line or Selected" by pydocstring`: 
```
Error on request (doCodeAction): Vim(return):Error invoking 'doCodeAction' on channel 3 (coc):
TypeError: document.getText is not a function
```
note that `CocCommand pydocstring.runFile` works well.

Config:
nvim : v0.8.0-dev+448-g7b2b44bce
coc-pydocstring: 0.7.3 
coc is up to date

doc is installed by `CocCommand pydocstring.install`

**Comment by yaegassy** [comment]
Thanks for the issue report. I am unable to reproduce this issue in my environment.

Can you give me the Pythoh code to reproduce?

**Comment by xavier-balesi** [comment]
a simple code with which I can reproduce : 
```
def hello(param: str = "world"):
    print(f"hello {param}")

```

steps:
- set cursor on the 'h' of 'hello'
- trigger `(coc-codeaction-line)`  (I use `:Telescope coc code_actions` for that)
- the floating window with codeactions-line is shown
- it contains the line `Add docstring for "Line or Selected" by pydocstring`
![image](https://user-images.githubusercontent.com/68602306/177020159-a0e21d14-79f2-4100-8b1f-b2b3b905d2d6.png)
- select this line then press `<CR>`
- the error happens
![image](https://user-images.githubusercontent.com/68602306/177020165-9d47a329-0c56-4e34-b1de-c846ac3e7a4f.png)

is the function `document.getText` must be in CocCommand ? I don't have it :
![image](https://user-images.githubusercontent.com/68602306/177020128-5378ec64-c517-4958-9c4f-74faf9384997.png)

Maybe you have some dependency that I didn't have installed...

**Comment by yaegassy** [comment]
Does it work correctly when run without telescope?

**Comment by xavier-balesi** [comment]
No it fails by the same way when I call <Plug>(coc-codeaction-line) : 
![image](https://user-images.githubusercontent.com/68602306/177039503-b3e2d438-b771-4e42-8d9f-b53f5dbf0324.png)
`[coc.nvim] Error on notification "doCodeAction": TypeError: document.getText is not a function`

But it works well when I call `CocCommand pydocstring.runFile` for the whole file.

**Comment by yaegassy** [comment]
I cannot reproduce this in my environment.

**DEMO (mp4)**:

https://user-images.githubusercontent.com/188642/177046257-c60bbdc4-6d1c-41cd-8307-42be60938f8e.mp4

**Comment by xavier-balesi** [comment]
I have fix the problem by changing two lines in function "activate"
I am not really confortable with js and COC lib and I'm not able to explain the bug, but now it seems to works well.

```js
  context.subscriptions.push(import_coc4.commands.registerCommand("pydocstring.runAction", async (document, range) => {
    const doc = import_coc4.workspace.getDocument(document.uri);
    let edits;
    const code = await doFormat(context, outputChannel, doc.textDocument, range); // document => doc.textDocument
    if (!range) {
      range = fullDocumentRange(document);
      edits = [import_coc4.TextEdit.replace(range, code)];
      if (edits) {
        return await doc.applyEdits(edits);
      }
    }
    if (doc.textDocument.getText() === code) { // document => doc.textDocument
      return;
    }
    edits = [import_coc4.TextEdit.replace(range, code)];
    if (edits) {
      return await doc.applyEdits(edits);
    }
  }, null, true));
```

**Comment by yaegassy** [comment]
Thanks for looking into the fixes. However, I think it is probably occurring because of the particular way you are executing CodeAction.

Would the same error occur if you execute a code action in your environment with the following mappings?


**Example key mapping**:

```
nmap <silent> ga <Plug>(coc-codeaction-line)
xmap <silent> ga <Plug>(coc-codeaction-selected)
```

**Comment by xavier-balesi** [comment]
OK !

I already tried by this way but I had the same issue.
but I removed a plugin that wrapped coc-action ([weilbith/nvim-code-action-menu](https://github.com/weilbith/nvim-code-action-menu)) and now it works (but not with telescope).

But maybe I could be interesting to make coc-pydocstring compatible with theses plugins.
Thanks for your help 👍🏽 .
