### ISSUE TITLE
please put the mappings on the README.md

### ISSUE THREAD

**Issue by SkyLeach** [yaegassy/coc-pydocstring#6]
# Please add some minimal mapping and remapping and usage documentation

At the time of me writing this I have absolutely no idea whatever what the
mappings are for per-line, per-selection or vim gestures to call
coc-pydocstring.  I've already walked through the coc-pydocstring-data which
appears to contain only the virtualenv used by your plugin to wrap calls to
doq.  I've already walked through the node-modules/coc-pydocstring path even
though I don't really know anything about coc modules and know little about the
node-coc-neovim plugin stack, which makes this exploration very slow for me.

I still haven't figured out where the vimscript command mappings are, there is
no vim documentation that I can find, and absolutely no hint that these
commands even exist other than the brief mention in the README.md.

I love your plugin, you've done a better job than I could have done with
implementation of a coc plugin, but I can't use anything except `:CocCommand
pydocstring-file` to make it work.  I don't even know what the hooks are in
order to create my own mappings.  Even the animated gif is missing any kind of
OSD keypress magic to show the viewer what keys are being pressed by the
author.

Thank you for your hard work and contribution!

**Comment by yaegassy** [comment]
Thanks for the issue report. I've added an example keymap to the README.
