### ISSUE TITLE
[question] Why a blank line will be generated at the end

### ISSUE THREAD

**Issue by Freed-Wu** [yaegassy/coc-pydocstring#9]
test.py

```python
def f(x):
    return x
```

after coc-pydocstring:

```python
def f(x):
    """f.

    :param x:
    """
    return x

```

A blank line occurs after `return x`.

Can it be deleted?

Thanks!

**Comment by yaegassy** [comment]
Thanks for reporting the issue. 🙇 I fixed it!

Run `:CocUpdate` to update the "coc-pydocstring".
